import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>25 + 5 Clock</title>
        <script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js" defer></script>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
